---
title: "4: List files"
author: David Wilkins
date: Generated `r lubridate::now()`
output:
  html_document:
    toc: true
    theme: readable
---

```{r global_options, include = FALSE}
library(knitr)
opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r message = FALSE}
library(tidyverse)
library(printr)
```


Next, download the list of files associated with each node.

```{r}
nodes$file <- map(nodes$node, osf_ls_files)
```

Tidy up the results.

```{r}
files <- nodes %>%
  mutate(osf_tbl_file = file) %>%
  unnest(node, names_sep = "_") %>%
  unnest(file, names_sep = "_") %>%
  mutate(kind = map_chr(file_meta, ~ .x$attributes$kind)) %>%
  select(-node_meta, -file_meta)
```

For results that are folders, download the list of files in that folder (will not try recursing deeper than one level).

```{r}
folders <- filter(files, kind == "folder")
files <- filter(files, kind == "file")

files <- files %>%
  mutate(folder = NA_character_) %>%
  select(-osf_tbl_file, -kind)

if (nrow(folders) > 0) {
  folders$file <- map(folders$osf_tbl_file, osf_ls_files)
  folders <- folders %>%
    rename(folder = file_name) %>%
    select(-osf_tbl_file, -kind, -file_id) %>%
    unnest(file, names_sep = "_") %>%
    select(-file_meta)
} else {
  folders <- files[0, ]
}

files <- bind_rows(files, folders)
```

The final list will be written for manual analysis.

```{r}
saveRDS(files, "potential_validation_files.rds")
```
